### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by ENikS** [reinaldocoelho/MailSystem.NET#1]
I've synced the repo. Please verify it was cloned without loosing anything.

**Comment by reinaldocoelho** [comment]
Apparently everything was successful.

It seems that some files were added outside the trunk folder that did not exist before. 
But trunk folder I guess does not make sense on Git.

I will create a README.md to the home page in the same way that there is on CodePlex and change the homepage of CodePlex to refer people to this project.

And we can focus on code that is here from now.

Thank you for making the migration, I really had not been able to do here :-(

**Comment by ENikS** [comment]
I am glad it worked out. Next time you need help with anything just open an issue and mark it as 'need help'. I am closing this issue.

**Comment by reinaldocoelho** [comment]
Ok. Thank you.
