### ISSUE TITLE
trunk folder

### ISSUE THREAD

**Issue by ENikS** [reinaldocoelho/MailSystem.NET#3]
Reinaldo, we could probably remove trunk folder all together?

**Comment by reinaldocoelho** [comment]
I'm sorry ENikS, I do not quite understand your question.

I did wrong to remove the Trunk folder and move the items to the base?

If I did I'm sorry, the intention was only to reorganize the repository.

But if so, we may create a modification process based on PullRequests, what you think about that?

**Comment by ENikS** [comment]
No, you did exactly what I was suggesting to do, remove the 'trunk'.

**Comment by reinaldocoelho** [comment]
Great :-)

But, realy, what you think about use PullRequest process to make changes on code?

I think it´s better because we will have double check and maintain a good code quality.

I have two changes to make, and if it´s a good idea, I can start request this changes.

**Comment by ENikS** [comment]
For new features, breaking changes and things you want other people opinions it would be great.
For changes that you know should be done just do direct push. No point to pull request simple stuff.

**Comment by reinaldocoelho** [comment]
Ok, fine :-)
