### ISSUE TITLE
Unable to delete messages from the inbox

### ISSUE THREAD

**Issue by godrose** [reinaldocoelho/MailSystem.NET#5]
Hi.
I'm trying to delete all messages from the *Inbox* mailbox using the package.
Here's the code:
```
     private void RegisterRepository()
     {
            iocContainer.RegisterInstance<IMailRepository>(new MailRepository("imap.gmail.com", 993, true,
            @"email@gmail.com", "password"));            
     }

    public interface IMailRepository
    {
        IEnumerable<Message> GetAllMails(string mailBox);
        IEnumerable<Message> GetUnreadMails(string mailBox);
        Message GetLastUnread(string mailBox);
        Message GetLast(string mailBox);
        void ClearMails(string mailBox);
    }

    public class MailRepository : IMailRepository
    {        
        public MailRepository(string mailServer, int port, bool ssl, string login, string password)
        {
            if (ssl)
            {
                Client.ConnectSsl(mailServer, port);
            }
            else
            {
                Client.Connect(mailServer, port);
            }                
            Client.Login(login, password);
        }

        public IEnumerable<Message> GetAllMails(string mailBox)
        {
            return GetMails(mailBox, "ALL").Cast<Message>();
        }

        public IEnumerable<Message> GetUnreadMails(string mailBox)
        {
            return GetMails(mailBox, "UNSEEN").Cast<Message>();
        }

        public Message GetLastUnread(string mailBox)
        {
            var mails = Client.SelectMailbox(mailBox);
            var ids = mails.Search(                                
                "UNSEEN"
                );
            return ids.Length == 0 ? null : mails.Fetch.MessageObject(ids.Last());
        }

        public Message GetLast(string mailBox)
        {
            var mails = Client.SelectMailbox(mailBox);
            var ids = mails.Search(
                "ALL"                
                );
            return ids.Length == 0 ? null : mails.Fetch.MessageObject(ids.Last());
        }

        public void ClearMails(string mailBox)
        {
            var mails = Client.SelectMailbox(mailBox);
            var ids = mails.Search("UNDELETED");
            foreach (var id in ids)
            {
                mails.DeleteMessage(id, expunge:true);
            }            
        }

        private Imap4Client _client;
        protected Imap4Client Client => _client ?? (_client = new Imap4Client());

        private MessageCollection GetMails(string mailBox, string searchPhrase)
        {
            Mailbox mails = Client.SelectMailbox(mailBox);
            MessageCollection messages = mails.SearchParse(searchPhrase);
            return messages;
        }
    }
```

The ```GetMails``` works as expected but the ```ClearEmails``` does not remove the emails from the inbox.
@reinaldocoelho

**Comment by reinaldocoelho** [comment]
Hi @godrose ,
    Thank you for the code.

    Tried you the same thing in other mail server like Hotmail or Yahoo?

     If not, can you test if the problem is only for Gmail, and we get a better focus to problem?

     Other question is: How you configured the IMAP on gmail? Because he has options who can change behavior.

     If the problem is only on Gmail, we can verify the problem.

Thank again.

**Comment by godrose** [comment]
Gmail Only.
No specific configuration, just the default.

**Comment by reinaldocoelho** [comment]
Can you send to us the configuration of SMTP on Gmail?

Even though the pattern, is interesting get the setting to try to simulate the problem.

Thank you.

**Comment by godrose** [comment]
Seems like it's an inconsistent bug. Sometimes it works

**Comment by reinaldocoelho** [comment]
Hi @godrose ,
I was studing the case and I did some tests.

I found the follow documentation of Gmail suggesting to move emails to Trash folder if you want to delete messages.
https://support.google.com/mail/answer/78755?hl=en

You tried this strategy?

Viewing the code, I not found bugs, the code is simple, he mark a Flag "Deleted" on email.

Follow the code to do This:

        public void delete_inbox_undeleted_messages_gmail()
        {
            var _selectedMailBox = "INBOX";
            using (var _clientImap4 = new Imap4Client())
            {
                _clientImap4.ConnectSsl(_imapServerAddress, _imapPort);
                _clientImap4.LoginFast(_imapLogin, _imapPassword);

                // To see the names os all MailBox and found  Trash
                //_clientImap4.LoadMailboxes();
                //var allMailBox = _clientImap4.AllMailboxes;

                var mails = _clientImap4.SelectMailbox(_selectedMailBox);
                var ids = mails.Search("UNDELETED");
                foreach (var id in ids)
                {
                    mails.MoveMessage(id, "[Gmail]/Trash");
                }

                var mailsUndeleted = _clientImap4.SelectMailbox(_selectedMailBox);
                Assert.AreEqual(0, mailsUndeleted.Search("UNDELETED"));

                _clientImap4.Disconnect();
            }
        }

If you need more help, please fell free.

Thank you.
